# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js App Deploy

on: [push]

jobs:
  deploy:
    runs-on: self-hosted
    steps:      
      - name: Checkout repository
        uses: actions/checkout@v4   

      - name: Deploy de app
        run: |
          cd /home/ubuntu/actions-runner/_work/nodejsapp/nodejsapp
          npm install # Instala dependencias si es necesario
          pm2 restart nodeapp # Reinicia el servidor Node.js usando PM2
